[2024-06-25T00:16:29.703+0000] {processor.py:161} INFO - Started process (PID=928) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T00:16:29.704+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T00:16:29.705+0000] {logging_mixin.py:188} INFO - [2024-06-25T00:16:29.705+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T00:16:29.711+0000] {logging_mixin.py:188} INFO - [2024-06-25T00:16:29.710+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T00:16:29.711+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T00:16:29.723+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.025 seconds
[2024-06-25T00:56:03.479+0000] {processor.py:161} INFO - Started process (PID=940) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T00:56:03.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T00:56:03.481+0000] {logging_mixin.py:188} INFO - [2024-06-25T00:56:03.481+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T00:56:03.486+0000] {logging_mixin.py:188} INFO - [2024-06-25T00:56:03.485+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T00:56:03.487+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T00:56:03.498+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.025 seconds
[2024-06-25T01:33:48.348+0000] {processor.py:161} INFO - Started process (PID=952) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T01:33:48.349+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T01:33:48.350+0000] {logging_mixin.py:188} INFO - [2024-06-25T01:33:48.350+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T01:33:48.356+0000] {logging_mixin.py:188} INFO - [2024-06-25T01:33:48.355+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T01:33:48.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T01:33:48.368+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.025 seconds
[2024-06-25T01:34:02.882+0000] {processor.py:161} INFO - Started process (PID=964) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T01:34:02.884+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T01:34:02.885+0000] {logging_mixin.py:188} INFO - [2024-06-25T01:34:02.884+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T01:34:02.895+0000] {logging_mixin.py:188} INFO - [2024-06-25T01:34:02.894+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T01:34:02.896+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T01:34:02.907+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.036 seconds
[2024-06-25T16:10:21.165+0000] {processor.py:161} INFO - Started process (PID=13) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:10:21.167+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:10:21.169+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:10:21.168+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:10:21.179+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:10:21.177+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:10:21.179+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:10:21.192+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.030 seconds
[2024-06-25T16:10:39.312+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:10:39.313+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:10:39.315+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:10:39.315+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:10:39.324+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:10:39.323+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:10:39.325+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:10:39.338+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.033 seconds
[2024-06-25T16:11:09.613+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:11:09.615+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:11:09.617+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:11:09.617+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:11:09.626+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:11:09.624+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:11:09.627+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:11:09.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.034 seconds
[2024-06-25T16:11:39.909+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:11:39.910+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:11:39.912+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:11:39.912+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:11:39.920+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:11:39.919+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:11:39.921+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:11:39.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.031 seconds
[2024-06-25T16:12:10.188+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:12:10.189+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:12:10.190+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:12:10.189+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:12:10.192+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:12:10.192+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:12:10.193+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:12:10.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.013 seconds
[2024-06-25T16:12:40.518+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:12:40.519+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:12:40.519+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:12:40.519+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:12:40.523+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:12:40.522+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:12:40.523+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:12:40.531+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.016 seconds
[2024-06-25T16:13:10.835+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:13:10.836+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:13:10.838+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:13:10.837+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:13:10.845+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:13:10.843+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:13:10.845+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:13:10.858+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.030 seconds
[2024-06-25T16:13:41.428+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:13:41.429+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:13:41.432+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:13:41.431+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:13:41.440+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:13:41.438+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:13:41.440+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:13:41.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.032 seconds
[2024-06-25T16:14:11.906+0000] {processor.py:161} INFO - Started process (PID=115) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:14:11.907+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:14:11.910+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:14:11.909+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:14:11.918+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:14:11.916+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:14:11.918+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:14:11.933+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.035 seconds
[2024-06-25T16:14:42.146+0000] {processor.py:161} INFO - Started process (PID=127) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:14:42.147+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:14:42.149+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:14:42.149+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:14:42.157+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:14:42.155+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:14:42.157+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:14:42.170+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.032 seconds
[2024-06-25T16:15:12.378+0000] {processor.py:161} INFO - Started process (PID=139) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:15:12.379+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:15:12.382+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:15:12.381+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:15:12.390+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:15:12.389+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:15:12.391+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:15:12.404+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.033 seconds
[2024-06-25T16:15:42.550+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:15:42.551+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:15:42.553+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:15:42.553+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:15:42.560+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:15:42.559+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:15:42.561+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:15:42.574+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.032 seconds
[2024-06-25T16:16:12.793+0000] {processor.py:161} INFO - Started process (PID=163) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:16:12.795+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:16:12.797+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:16:12.797+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:16:12.806+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:16:12.805+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:16:12.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:16:12.820+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.035 seconds
[2024-06-25T16:16:43.039+0000] {processor.py:161} INFO - Started process (PID=175) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:16:43.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:16:43.044+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:16:43.043+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:16:43.051+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:16:43.050+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:16:43.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:16:43.066+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.034 seconds
[2024-06-25T16:17:13.276+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:17:13.277+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:17:13.280+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:17:13.279+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:17:13.287+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:17:13.286+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:17:13.288+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:17:13.301+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.032 seconds
[2024-06-25T16:17:43.518+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:17:43.520+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:17:43.523+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:17:43.522+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:17:43.532+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:17:43.530+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:17:43.532+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:17:43.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.034 seconds
[2024-06-25T16:18:13.751+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:18:13.753+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:18:13.756+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:18:13.755+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:18:13.764+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:18:13.763+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:18:13.765+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:18:13.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.033 seconds
[2024-06-25T16:18:43.922+0000] {processor.py:161} INFO - Started process (PID=223) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:18:43.923+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:18:43.924+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:18:43.923+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:18:43.927+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:18:43.926+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:18:43.927+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:18:43.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.015 seconds
[2024-06-25T16:19:14.168+0000] {processor.py:161} INFO - Started process (PID=235) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:19:14.169+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:19:14.172+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:19:14.172+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:19:14.182+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:19:14.180+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:19:14.182+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:19:14.198+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.041 seconds
[2024-06-25T16:19:44.719+0000] {processor.py:161} INFO - Started process (PID=247) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:19:44.720+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:19:44.722+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:19:44.722+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:19:44.730+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:19:44.728+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:19:44.731+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:19:44.745+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.034 seconds
[2024-06-25T16:20:15.266+0000] {processor.py:161} INFO - Started process (PID=259) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:20:15.267+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:20:15.270+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:20:15.269+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:20:15.278+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:20:15.276+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:20:15.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:20:15.293+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.034 seconds
[2024-06-25T16:20:45.696+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:20:45.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:20:45.699+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:20:45.698+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:20:45.706+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:20:45.705+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:20:45.707+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:20:45.718+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.029 seconds
[2024-06-25T16:21:16.250+0000] {processor.py:161} INFO - Started process (PID=283) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:21:16.251+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:21:16.252+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:21:16.252+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:21:16.261+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:21:16.260+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:21:16.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:21:16.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.030 seconds
[2024-06-25T16:21:46.805+0000] {processor.py:161} INFO - Started process (PID=295) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:21:46.807+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:21:46.808+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:21:46.808+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:21:46.817+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:21:46.815+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:21:46.818+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:21:46.831+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.032 seconds
[2024-06-25T16:22:17.271+0000] {processor.py:161} INFO - Started process (PID=307) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:22:17.272+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:22:17.275+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:22:17.275+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:22:17.283+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:22:17.282+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:22:17.284+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:22:17.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.032 seconds
[2024-06-25T16:22:47.718+0000] {processor.py:161} INFO - Started process (PID=319) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:22:47.720+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:22:47.723+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:22:47.722+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:22:47.732+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:22:47.730+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:22:47.733+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:22:47.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.037 seconds
[2024-06-25T16:23:18.166+0000] {processor.py:161} INFO - Started process (PID=331) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:23:18.167+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:23:18.169+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:23:18.169+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:23:18.179+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:23:18.178+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:23:18.180+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:23:18.193+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.033 seconds
[2024-06-25T16:23:48.730+0000] {processor.py:161} INFO - Started process (PID=343) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:23:48.732+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:23:48.734+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:23:48.733+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:23:48.741+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:23:48.740+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:23:48.742+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:23:48.755+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.031 seconds
[2024-06-25T16:24:19.024+0000] {processor.py:161} INFO - Started process (PID=355) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:24:19.025+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:24:19.027+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:24:19.027+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:24:19.035+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:24:19.033+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:24:19.036+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:24:19.049+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.033 seconds
[2024-06-25T16:24:49.302+0000] {processor.py:161} INFO - Started process (PID=367) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:24:49.304+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:24:49.306+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:24:49.305+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:24:49.314+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:24:49.312+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:24:49.314+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:24:49.329+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.034 seconds
[2024-06-25T16:25:19.695+0000] {processor.py:161} INFO - Started process (PID=379) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:25:19.696+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:25:19.698+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:25:19.698+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:25:19.706+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:25:19.704+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:25:19.707+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:25:19.720+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.033 seconds
[2024-06-25T16:25:49.978+0000] {processor.py:161} INFO - Started process (PID=391) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:25:49.979+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:25:49.982+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:25:49.982+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:25:49.991+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:25:49.989+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:25:49.992+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:25:50.005+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.035 seconds
[2024-06-25T16:26:20.357+0000] {processor.py:161} INFO - Started process (PID=403) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:26:20.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:26:20.361+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:26:20.361+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:26:20.366+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:26:20.365+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:26:20.366+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:26:20.377+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.024 seconds
[2024-06-25T16:26:50.635+0000] {processor.py:161} INFO - Started process (PID=415) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:26:50.637+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:26:50.638+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:26:50.638+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:26:50.644+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:26:50.643+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:26:50.645+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:26:50.656+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.025 seconds
[2024-06-25T16:27:21.048+0000] {processor.py:161} INFO - Started process (PID=427) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:27:21.050+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:27:21.052+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:27:21.051+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:27:21.060+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:27:21.058+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:27:21.060+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:27:21.073+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.032 seconds
[2024-06-25T16:27:51.422+0000] {processor.py:161} INFO - Started process (PID=439) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:27:51.424+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:27:51.427+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:27:51.426+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:27:51.435+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:27:51.433+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:27:51.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:27:51.449+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.034 seconds
[2024-06-25T16:28:21.707+0000] {processor.py:161} INFO - Started process (PID=451) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:28:21.709+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:28:21.711+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:28:21.710+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:28:21.719+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:28:21.717+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:28:21.720+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:28:21.732+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.032 seconds
[2024-06-25T16:28:51.999+0000] {processor.py:161} INFO - Started process (PID=474) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:28:52.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:28:52.002+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:28:52.002+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:28:52.008+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:28:52.007+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:28:52.009+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:28:52.021+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.027 seconds
[2024-06-25T16:29:22.191+0000] {processor.py:161} INFO - Started process (PID=486) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:29:22.191+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:29:22.192+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:29:22.192+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:29:22.197+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:29:22.196+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:29:22.197+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:29:22.207+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.021 seconds
[2024-06-25T16:29:52.414+0000] {processor.py:161} INFO - Started process (PID=498) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:29:52.415+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:29:52.417+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:29:52.416+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:29:52.421+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:29:52.420+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:29:52.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:29:52.429+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.021 seconds
[2024-06-25T16:30:22.667+0000] {processor.py:161} INFO - Started process (PID=510) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:30:22.668+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:30:22.671+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:30:22.670+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:30:22.678+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:30:22.676+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:30:22.679+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:30:22.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.034 seconds
[2024-06-25T16:30:52.914+0000] {processor.py:161} INFO - Started process (PID=522) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:30:52.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:30:52.918+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:30:52.918+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:30:52.926+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:30:52.925+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:30:52.927+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:30:52.941+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.033 seconds
[2024-06-25T16:31:23.026+0000] {processor.py:161} INFO - Started process (PID=534) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:31:23.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:31:23.029+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:31:23.029+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:31:23.037+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:31:23.035+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:31:23.037+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:31:23.049+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.029 seconds
[2024-06-25T16:31:53.789+0000] {processor.py:161} INFO - Started process (PID=546) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:31:53.790+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:31:53.792+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:31:53.791+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:31:53.800+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:31:53.798+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:31:53.801+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:31:53.814+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.030 seconds
[2024-06-25T16:32:24.102+0000] {processor.py:161} INFO - Started process (PID=558) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:32:24.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:32:24.103+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:32:24.103+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:32:24.107+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:32:24.106+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:32:24.107+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:32:24.117+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.019 seconds
[2024-06-25T16:32:54.768+0000] {processor.py:161} INFO - Started process (PID=570) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:32:54.769+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:32:54.772+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:32:54.772+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:32:54.780+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:32:54.779+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:32:54.781+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:32:54.795+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.034 seconds
[2024-06-25T16:33:25.167+0000] {processor.py:161} INFO - Started process (PID=582) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:33:25.168+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:33:25.171+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:33:25.170+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:33:25.177+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:33:25.176+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:33:25.178+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:33:25.189+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.029 seconds
[2024-06-25T16:33:55.755+0000] {processor.py:161} INFO - Started process (PID=594) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:33:55.756+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:33:55.759+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:33:55.759+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:33:55.767+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:33:55.766+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:33:55.768+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:33:55.782+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.034 seconds
[2024-06-25T16:34:25.994+0000] {processor.py:161} INFO - Started process (PID=606) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:34:25.996+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:34:25.998+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:34:25.998+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:34:26.006+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:34:26.004+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:34:26.006+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:34:26.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.033 seconds
[2024-06-25T16:34:56.235+0000] {processor.py:161} INFO - Started process (PID=629) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:34:56.237+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:34:56.239+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:34:56.238+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:34:56.246+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:34:56.244+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:34:56.246+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:34:56.260+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.033 seconds
[2024-06-25T16:35:26.377+0000] {processor.py:161} INFO - Started process (PID=641) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:35:26.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:35:26.380+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:35:26.380+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:35:26.389+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:35:26.388+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:35:26.390+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:35:26.404+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.034 seconds
[2024-06-25T16:35:56.594+0000] {processor.py:161} INFO - Started process (PID=653) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:35:56.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:35:56.598+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:35:56.597+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:35:56.604+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:35:56.603+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:35:56.605+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:35:56.621+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.033 seconds
[2024-06-25T16:36:26.838+0000] {processor.py:161} INFO - Started process (PID=665) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:36:26.840+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:36:26.842+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:36:26.842+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:36:26.850+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:36:26.849+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:36:26.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:36:26.865+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.033 seconds
[2024-06-25T16:36:57.070+0000] {processor.py:161} INFO - Started process (PID=677) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:36:57.071+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:36:57.073+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:36:57.073+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:36:57.082+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:36:57.080+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:36:57.082+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:36:57.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.035 seconds
[2024-06-25T16:37:27.254+0000] {processor.py:161} INFO - Started process (PID=689) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:37:27.256+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:37:27.258+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:37:27.258+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:37:27.266+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:37:27.264+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:37:27.267+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:37:27.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.037 seconds
[2024-06-25T16:37:57.485+0000] {processor.py:161} INFO - Started process (PID=701) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:37:57.486+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:37:57.489+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:37:57.489+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:37:57.497+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:37:57.496+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:37:57.498+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:37:57.514+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.037 seconds
[2024-06-25T16:38:27.721+0000] {processor.py:161} INFO - Started process (PID=713) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:38:27.722+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:38:27.724+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:38:27.724+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:38:27.732+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:38:27.731+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:38:27.733+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:38:27.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.034 seconds
[2024-06-25T16:38:57.876+0000] {processor.py:161} INFO - Started process (PID=736) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:38:57.878+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:38:57.880+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:38:57.879+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:38:57.885+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:38:57.884+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:38:57.885+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:38:57.894+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.025 seconds
[2024-06-25T16:39:28.105+0000] {processor.py:161} INFO - Started process (PID=748) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:39:28.107+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:39:28.110+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:39:28.109+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:39:28.120+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:39:28.118+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:39:28.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:39:28.135+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.037 seconds
[2024-06-25T16:39:58.341+0000] {processor.py:161} INFO - Started process (PID=760) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:39:58.343+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:39:58.345+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:39:58.345+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:39:58.353+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:39:58.351+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:39:58.353+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:39:58.367+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.033 seconds
[2024-06-25T16:40:28.574+0000] {processor.py:161} INFO - Started process (PID=772) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:40:28.575+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:40:28.578+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:40:28.578+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:40:28.585+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:40:28.584+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:40:28.586+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:40:28.600+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.033 seconds
[2024-06-25T16:40:58.812+0000] {processor.py:161} INFO - Started process (PID=784) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:40:58.813+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:40:58.816+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:40:58.815+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:40:58.823+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:40:58.822+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:40:58.823+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:40:58.837+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.032 seconds
[2024-06-25T16:41:29.020+0000] {processor.py:161} INFO - Started process (PID=796) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:41:29.021+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:41:29.024+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:41:29.024+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:41:29.032+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:41:29.030+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:41:29.032+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:41:29.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.034 seconds
[2024-06-25T16:41:59.314+0000] {processor.py:161} INFO - Started process (PID=808) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:41:59.315+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:41:59.317+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:41:59.317+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:41:59.325+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:41:59.323+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:41:59.325+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:41:59.339+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.032 seconds
[2024-06-25T16:42:29.450+0000] {processor.py:161} INFO - Started process (PID=820) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:42:29.451+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:42:29.452+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:42:29.452+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:42:29.459+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:42:29.458+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:42:29.460+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:42:29.471+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.028 seconds
[2024-06-25T16:42:59.719+0000] {processor.py:161} INFO - Started process (PID=832) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:42:59.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:42:59.723+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:42:59.722+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:42:59.730+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:42:59.729+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:42:59.731+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:42:59.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.035 seconds
[2024-06-25T16:43:29.969+0000] {processor.py:161} INFO - Started process (PID=844) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:43:29.970+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:43:29.973+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:43:29.972+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:43:29.979+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:43:29.978+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:43:29.980+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:43:29.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.033 seconds
[2024-06-25T16:44:00.169+0000] {processor.py:161} INFO - Started process (PID=856) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:44:00.170+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:44:00.173+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:00.172+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:44:00.181+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:00.179+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:44:00.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:44:00.196+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.037 seconds
[2024-06-25T16:44:14.854+0000] {processor.py:161} INFO - Started process (PID=868) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:44:14.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:44:14.858+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:14.857+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:44:14.868+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:14.867+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 70, in <module>
    bla = PythonOpera
          ^^^^^^^^^^^
NameError: name 'PythonOpera' is not defined
[2024-06-25T16:44:14.869+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:44:14.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 0.035 seconds
[2024-06-25T16:44:21.818+0000] {processor.py:161} INFO - Started process (PID=869) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:44:21.820+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:44:21.822+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:21.821+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:44:21.833+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:21.832+0000] {graph.py:242} INFO - Trying to parse the dbt project in `/opt/airflow/dbt_tp` using dbt ls...
[2024-06-25T16:44:21.835+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:21.835+0000] {graph.py:252} INFO - Content of the dbt project dir /opt/airflow/dbt_tp: `['.user.yml', 'dependencies.yml', 'profiles.yml', 'snapshots', 'package-lock.yml', 'Dockerfile', 'tests', 'models', 'README.md', 'macros', '.dockerignore', '.gitignore', 'seeds', 'analyses', 'dbt_project.yml']`
[2024-06-25T16:44:21.837+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:21.837+0000] {graph.py:262} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/run_dbt__dbt_task_group/target/partial_parse.msgpack
[2024-06-25T16:44:21.846+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:21.846+0000] {base.py:222} INFO - Using mock values for profile dbt_tp
[2024-06-25T16:44:21.847+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:21.847+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=True at /tmp/tmph18wnmis/profiles.yml with the following contents:
dbt_tp:
    outputs:
        dev:
            dbname: postgres
            host: mock_value
            password: mock_value
            port: 5432
            schema: public
            type: postgres
            user: mock_value
    target: dev
[2024-06-25T16:44:21.848+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:21.848+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt deps --project-dir /tmp/tmpjb2wis9f --profiles-dir /tmp/tmph18wnmis --profile dbt_tp --target dev`
[2024-06-25T16:44:26.890+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:26.889+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt ls --output json --project-dir /tmp/tmpjb2wis9f --profiles-dir /tmp/tmph18wnmis --profile dbt_tp --target dev`
[2024-06-25T16:44:30.256+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:30.256+0000] {graph.py:190} INFO - Total nodes: 6
[2024-06-25T16:44:30.257+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:30.257+0000] {graph.py:191} INFO - Total filtered nodes: 6
[2024-06-25T16:44:30.259+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:30.258+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/run_dbt.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dbt.py", line 89, in <module>
    bla >> dbt_task_group >> generate_dbt_docs
    ^^^
NameError: name 'bla' is not defined
[2024-06-25T16:44:30.259+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:44:30.269+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 8.457 seconds
[2024-06-25T16:44:34.527+0000] {processor.py:161} INFO - Started process (PID=875) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:44:34.528+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:44:34.528+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:34.528+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:44:34.535+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:34.535+0000] {graph.py:242} INFO - Trying to parse the dbt project in `/opt/airflow/dbt_tp` using dbt ls...
[2024-06-25T16:44:34.536+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:34.536+0000] {graph.py:252} INFO - Content of the dbt project dir /opt/airflow/dbt_tp: `['.user.yml', 'dependencies.yml', 'profiles.yml', 'snapshots', 'package-lock.yml', 'Dockerfile', 'tests', 'models', 'README.md', 'macros', '.dockerignore', '.gitignore', 'seeds', 'analyses', 'dbt_project.yml']`
[2024-06-25T16:44:34.537+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:34.537+0000] {graph.py:262} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/run_dbt__dbt_task_group/target/partial_parse.msgpack
[2024-06-25T16:44:34.542+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:34.542+0000] {base.py:222} INFO - Using mock values for profile dbt_tp
[2024-06-25T16:44:34.543+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:34.543+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=True at /tmp/tmpxnqxnixa/profiles.yml with the following contents:
dbt_tp:
    outputs:
        dev:
            dbname: postgres
            host: mock_value
            password: mock_value
            port: 5432
            schema: public
            type: postgres
            user: mock_value
    target: dev
[2024-06-25T16:44:34.544+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:34.544+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt deps --project-dir /tmp/tmp7hqj1kfc --profiles-dir /tmp/tmpxnqxnixa --profile dbt_tp --target dev`
[2024-06-25T16:44:37.788+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:37.788+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt ls --output json --project-dir /tmp/tmp7hqj1kfc --profiles-dir /tmp/tmpxnqxnixa --profile dbt_tp --target dev`
[2024-06-25T16:44:39.253+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:39.253+0000] {graph.py:190} INFO - Total nodes: 6
[2024-06-25T16:44:39.253+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:39.253+0000] {graph.py:191} INFO - Total filtered nodes: 6
[2024-06-25T16:44:39.255+0000] {processor.py:840} INFO - DAG(s) 'run_dbt' retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:44:39.275+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:39.275+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-25T16:44:39.278+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:44:39.278+0000] {dag.py:3954} INFO - Setting next_dagrun for run_dbt to None, run_after=None
[2024-06-25T16:44:39.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 4.767 seconds
[2024-06-25T16:45:29.532+0000] {processor.py:161} INFO - Started process (PID=13) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:45:29.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:45:29.534+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:45:29.534+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:45:29.539+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:45:29.539+0000] {graph.py:242} INFO - Trying to parse the dbt project in `/opt/airflow/dbt_tp` using dbt ls...
[2024-06-25T16:45:29.540+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:45:29.540+0000] {graph.py:252} INFO - Content of the dbt project dir /opt/airflow/dbt_tp: `['.user.yml', 'dependencies.yml', 'profiles.yml', 'snapshots', 'package-lock.yml', 'Dockerfile', 'tests', 'models', 'README.md', 'macros', '.dockerignore', '.gitignore', 'seeds', 'analyses', 'dbt_project.yml']`
[2024-06-25T16:45:29.541+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:45:29.541+0000] {graph.py:262} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/run_dbt__dbt_task_group/target/partial_parse.msgpack
[2024-06-25T16:45:29.546+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:45:29.545+0000] {base.py:222} INFO - Using mock values for profile dbt_tp
[2024-06-25T16:45:29.547+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:45:29.546+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=True at /tmp/tmpsgflru5a/profiles.yml with the following contents:
dbt_tp:
    outputs:
        dev:
            dbname: postgres
            host: mock_value
            password: mock_value
            port: 5432
            schema: public
            type: postgres
            user: mock_value
    target: dev
[2024-06-25T16:45:29.547+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:45:29.547+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt deps --project-dir /tmp/tmpdt8_20qq --profiles-dir /tmp/tmpsgflru5a --profile dbt_tp --target dev`
[2024-06-25T16:45:31.949+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:45:31.949+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt ls --output json --project-dir /tmp/tmpdt8_20qq --profiles-dir /tmp/tmpsgflru5a --profile dbt_tp --target dev`
[2024-06-25T16:45:33.411+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:45:33.411+0000] {graph.py:190} INFO - Total nodes: 6
[2024-06-25T16:45:33.412+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:45:33.412+0000] {graph.py:191} INFO - Total filtered nodes: 6
[2024-06-25T16:45:33.413+0000] {processor.py:840} INFO - DAG(s) 'run_dbt' retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:45:33.423+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:45:33.423+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-25T16:45:33.427+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:45:33.427+0000] {dag.py:3954} INFO - Setting next_dagrun for run_dbt to None, run_after=None
[2024-06-25T16:45:33.437+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 3.908 seconds
[2024-06-25T16:46:04.296+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:46:04.297+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:46:04.299+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:04.299+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:46:04.308+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:04.307+0000] {graph.py:242} INFO - Trying to parse the dbt project in `/opt/airflow/dbt_tp` using dbt ls...
[2024-06-25T16:46:04.310+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:04.310+0000] {graph.py:252} INFO - Content of the dbt project dir /opt/airflow/dbt_tp: `['.user.yml', 'dependencies.yml', 'profiles.yml', 'snapshots', 'package-lock.yml', 'Dockerfile', 'tests', 'models', 'README.md', 'macros', '.dockerignore', '.gitignore', 'seeds', 'analyses', 'dbt_project.yml']`
[2024-06-25T16:46:04.312+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:04.312+0000] {graph.py:262} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/run_dbt__dbt_task_group/target/partial_parse.msgpack
[2024-06-25T16:46:04.319+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:04.319+0000] {base.py:222} INFO - Using mock values for profile dbt_tp
[2024-06-25T16:46:04.320+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:04.320+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=True at /tmp/tmpfency0y1/profiles.yml with the following contents:
dbt_tp:
    outputs:
        dev:
            dbname: postgres
            host: mock_value
            password: mock_value
            port: 5432
            schema: public
            type: postgres
            user: mock_value
    target: dev
[2024-06-25T16:46:04.321+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:04.321+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt deps --project-dir /tmp/tmp0r57p7lz --profiles-dir /tmp/tmpfency0y1 --profile dbt_tp --target dev`
[2024-06-25T16:46:07.234+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:07.233+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt ls --output json --project-dir /tmp/tmp0r57p7lz --profiles-dir /tmp/tmpfency0y1 --profile dbt_tp --target dev`
[2024-06-25T16:46:08.962+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:08.962+0000] {graph.py:190} INFO - Total nodes: 6
[2024-06-25T16:46:08.962+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:08.962+0000] {graph.py:191} INFO - Total filtered nodes: 6
[2024-06-25T16:46:08.964+0000] {processor.py:840} INFO - DAG(s) 'run_dbt' retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:46:08.973+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:08.973+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-25T16:46:08.976+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:08.976+0000] {dag.py:3954} INFO - Setting next_dagrun for run_dbt to None, run_after=None
[2024-06-25T16:46:08.984+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 4.695 seconds
[2024-06-25T16:46:39.365+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:46:39.366+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:46:39.368+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:39.367+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:46:39.378+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:39.378+0000] {graph.py:242} INFO - Trying to parse the dbt project in `/opt/airflow/dbt_tp` using dbt ls...
[2024-06-25T16:46:39.380+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:39.380+0000] {graph.py:252} INFO - Content of the dbt project dir /opt/airflow/dbt_tp: `['.user.yml', 'dependencies.yml', 'profiles.yml', 'snapshots', 'package-lock.yml', 'Dockerfile', 'tests', 'models', 'README.md', 'macros', '.dockerignore', '.gitignore', 'seeds', 'analyses', 'dbt_project.yml']`
[2024-06-25T16:46:39.382+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:39.381+0000] {graph.py:262} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/run_dbt__dbt_task_group/target/partial_parse.msgpack
[2024-06-25T16:46:39.388+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:39.388+0000] {base.py:222} INFO - Using mock values for profile dbt_tp
[2024-06-25T16:46:39.389+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:39.389+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=True at /tmp/tmp7faqfay9/profiles.yml with the following contents:
dbt_tp:
    outputs:
        dev:
            dbname: postgres
            host: mock_value
            password: mock_value
            port: 5432
            schema: public
            type: postgres
            user: mock_value
    target: dev
[2024-06-25T16:46:39.390+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:39.389+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt deps --project-dir /tmp/tmpd30bisza --profiles-dir /tmp/tmp7faqfay9 --profile dbt_tp --target dev`
[2024-06-25T16:46:42.471+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:42.471+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt ls --output json --project-dir /tmp/tmpd30bisza --profiles-dir /tmp/tmp7faqfay9 --profile dbt_tp --target dev`
[2024-06-25T16:46:44.058+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:44.058+0000] {graph.py:190} INFO - Total nodes: 6
[2024-06-25T16:46:44.059+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:44.058+0000] {graph.py:191} INFO - Total filtered nodes: 6
[2024-06-25T16:46:44.061+0000] {processor.py:840} INFO - DAG(s) 'run_dbt' retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:46:44.072+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:44.072+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-25T16:46:44.076+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:46:44.076+0000] {dag.py:3954} INFO - Setting next_dagrun for run_dbt to None, run_after=None
[2024-06-25T16:46:44.086+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 4.728 seconds
[2024-06-25T16:47:14.332+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:47:14.334+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:47:14.337+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:14.336+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:47:14.346+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:14.346+0000] {graph.py:242} INFO - Trying to parse the dbt project in `/opt/airflow/dbt_tp` using dbt ls...
[2024-06-25T16:47:14.348+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:14.348+0000] {graph.py:252} INFO - Content of the dbt project dir /opt/airflow/dbt_tp: `['.user.yml', 'dependencies.yml', 'profiles.yml', 'snapshots', 'package-lock.yml', 'Dockerfile', 'tests', 'models', 'README.md', 'macros', '.dockerignore', '.gitignore', 'seeds', 'analyses', 'dbt_project.yml']`
[2024-06-25T16:47:14.350+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:14.350+0000] {graph.py:262} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/run_dbt__dbt_task_group/target/partial_parse.msgpack
[2024-06-25T16:47:14.357+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:14.357+0000] {base.py:222} INFO - Using mock values for profile dbt_tp
[2024-06-25T16:47:14.359+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:14.359+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=True at /tmp/tmpi_e2igu3/profiles.yml with the following contents:
dbt_tp:
    outputs:
        dev:
            dbname: postgres
            host: mock_value
            password: mock_value
            port: 5432
            schema: public
            type: postgres
            user: mock_value
    target: dev
[2024-06-25T16:47:14.359+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:14.359+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt deps --project-dir /tmp/tmpcclgjien --profiles-dir /tmp/tmpi_e2igu3 --profile dbt_tp --target dev`
[2024-06-25T16:47:18.859+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:18.858+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt ls --output json --project-dir /tmp/tmpcclgjien --profiles-dir /tmp/tmpi_e2igu3 --profile dbt_tp --target dev`
[2024-06-25T16:47:20.353+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:20.353+0000] {graph.py:190} INFO - Total nodes: 6
[2024-06-25T16:47:20.354+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:20.354+0000] {graph.py:191} INFO - Total filtered nodes: 6
[2024-06-25T16:47:20.356+0000] {processor.py:840} INFO - DAG(s) 'run_dbt' retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:47:20.414+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:20.413+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-25T16:47:20.417+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:20.417+0000] {dag.py:3954} INFO - Setting next_dagrun for run_dbt to None, run_after=None
[2024-06-25T16:47:20.429+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 6.105 seconds
[2024-06-25T16:47:50.551+0000] {processor.py:161} INFO - Started process (PID=145) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:47:50.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:47:50.553+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:50.553+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:47:50.559+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:50.559+0000] {graph.py:242} INFO - Trying to parse the dbt project in `/opt/airflow/dbt_tp` using dbt ls...
[2024-06-25T16:47:50.561+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:50.561+0000] {graph.py:252} INFO - Content of the dbt project dir /opt/airflow/dbt_tp: `['.user.yml', 'dependencies.yml', 'profiles.yml', 'snapshots', 'package-lock.yml', 'Dockerfile', 'tests', 'models', 'README.md', 'macros', '.dockerignore', '.gitignore', 'seeds', 'analyses', 'dbt_project.yml']`
[2024-06-25T16:47:50.563+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:50.563+0000] {graph.py:262} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/run_dbt__dbt_task_group/target/partial_parse.msgpack
[2024-06-25T16:47:50.615+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:50.615+0000] {base.py:222} INFO - Using mock values for profile dbt_tp
[2024-06-25T16:47:50.616+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:50.616+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=True at /tmp/tmp63q4k8hs/profiles.yml with the following contents:
dbt_tp:
    outputs:
        dev:
            dbname: postgres
            host: mock_value
            password: mock_value
            port: 5432
            schema: public
            type: postgres
            user: mock_value
    target: dev
[2024-06-25T16:47:50.617+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:50.617+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt deps --project-dir /tmp/tmpz0awvul0 --profiles-dir /tmp/tmp63q4k8hs --profile dbt_tp --target dev`
[2024-06-25T16:47:54.528+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:54.528+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt ls --output json --project-dir /tmp/tmpz0awvul0 --profiles-dir /tmp/tmp63q4k8hs --profile dbt_tp --target dev`
[2024-06-25T16:47:56.636+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:56.635+0000] {graph.py:190} INFO - Total nodes: 6
[2024-06-25T16:47:56.636+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:56.636+0000] {graph.py:191} INFO - Total filtered nodes: 6
[2024-06-25T16:47:56.637+0000] {processor.py:840} INFO - DAG(s) 'run_dbt' retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:47:56.644+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:56.644+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-25T16:47:56.647+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:47:56.647+0000] {dag.py:3954} INFO - Setting next_dagrun for run_dbt to None, run_after=None
[2024-06-25T16:47:56.655+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 6.107 seconds
[2024-06-25T16:48:26.917+0000] {processor.py:161} INFO - Started process (PID=173) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:48:26.918+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:48:26.919+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:48:26.918+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:48:26.922+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:48:26.922+0000] {graph.py:242} INFO - Trying to parse the dbt project in `/opt/airflow/dbt_tp` using dbt ls...
[2024-06-25T16:48:26.923+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:48:26.923+0000] {graph.py:252} INFO - Content of the dbt project dir /opt/airflow/dbt_tp: `['.user.yml', 'dependencies.yml', 'profiles.yml', 'snapshots', 'package-lock.yml', 'Dockerfile', 'tests', 'models', 'README.md', 'macros', '.dockerignore', '.gitignore', 'seeds', 'analyses', 'dbt_project.yml']`
[2024-06-25T16:48:26.924+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:48:26.924+0000] {graph.py:262} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/run_dbt__dbt_task_group/target/partial_parse.msgpack
[2024-06-25T16:48:26.927+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:48:26.927+0000] {base.py:222} INFO - Using mock values for profile dbt_tp
[2024-06-25T16:48:26.928+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:48:26.928+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=True at /tmp/tmplzw8epwx/profiles.yml with the following contents:
dbt_tp:
    outputs:
        dev:
            dbname: postgres
            host: mock_value
            password: mock_value
            port: 5432
            schema: public
            type: postgres
            user: mock_value
    target: dev
[2024-06-25T16:48:26.928+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:48:26.928+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt deps --project-dir /tmp/tmpjwms4s0t --profiles-dir /tmp/tmplzw8epwx --profile dbt_tp --target dev`
[2024-06-25T16:48:31.279+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:48:31.279+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt ls --output json --project-dir /tmp/tmpjwms4s0t --profiles-dir /tmp/tmplzw8epwx --profile dbt_tp --target dev`
[2024-06-25T16:48:33.394+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:48:33.394+0000] {graph.py:190} INFO - Total nodes: 6
[2024-06-25T16:48:33.395+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:48:33.394+0000] {graph.py:191} INFO - Total filtered nodes: 6
[2024-06-25T16:48:33.397+0000] {processor.py:840} INFO - DAG(s) 'run_dbt' retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:48:33.408+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:48:33.408+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-25T16:48:33.413+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:48:33.413+0000] {dag.py:3954} INFO - Setting next_dagrun for run_dbt to None, run_after=None
[2024-06-25T16:48:33.422+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 6.507 seconds
[2024-06-25T16:49:03.603+0000] {processor.py:161} INFO - Started process (PID=190) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:49:03.605+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:49:03.607+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:03.607+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:49:03.616+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:03.616+0000] {graph.py:242} INFO - Trying to parse the dbt project in `/opt/airflow/dbt_tp` using dbt ls...
[2024-06-25T16:49:03.619+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:03.618+0000] {graph.py:252} INFO - Content of the dbt project dir /opt/airflow/dbt_tp: `['.user.yml', 'dependencies.yml', 'profiles.yml', 'snapshots', 'package-lock.yml', 'Dockerfile', 'tests', 'models', 'README.md', 'macros', '.dockerignore', '.gitignore', 'seeds', 'analyses', 'dbt_project.yml']`
[2024-06-25T16:49:03.620+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:03.620+0000] {graph.py:262} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/run_dbt__dbt_task_group/target/partial_parse.msgpack
[2024-06-25T16:49:03.628+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:03.627+0000] {base.py:222} INFO - Using mock values for profile dbt_tp
[2024-06-25T16:49:03.629+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:03.629+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=True at /tmp/tmp3v_id9nx/profiles.yml with the following contents:
dbt_tp:
    outputs:
        dev:
            dbname: postgres
            host: mock_value
            password: mock_value
            port: 5432
            schema: public
            type: postgres
            user: mock_value
    target: dev
[2024-06-25T16:49:03.630+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:03.630+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt deps --project-dir /tmp/tmpm9jxyjc3 --profiles-dir /tmp/tmp3v_id9nx --profile dbt_tp --target dev`
[2024-06-25T16:49:08.218+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:08.217+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt ls --output json --project-dir /tmp/tmpm9jxyjc3 --profiles-dir /tmp/tmp3v_id9nx --profile dbt_tp --target dev`
[2024-06-25T16:49:09.764+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:09.764+0000] {graph.py:190} INFO - Total nodes: 6
[2024-06-25T16:49:09.764+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:09.764+0000] {graph.py:191} INFO - Total filtered nodes: 6
[2024-06-25T16:49:09.766+0000] {processor.py:840} INFO - DAG(s) 'run_dbt' retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:49:09.774+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:09.774+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-25T16:49:09.777+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:09.777+0000] {dag.py:3954} INFO - Setting next_dagrun for run_dbt to None, run_after=None
[2024-06-25T16:49:09.785+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 6.188 seconds
[2024-06-25T16:49:39.897+0000] {processor.py:161} INFO - Started process (PID=229) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:49:39.904+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:49:39.906+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:39.905+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:49:39.912+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:39.912+0000] {graph.py:242} INFO - Trying to parse the dbt project in `/opt/airflow/dbt_tp` using dbt ls...
[2024-06-25T16:49:39.914+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:39.914+0000] {graph.py:252} INFO - Content of the dbt project dir /opt/airflow/dbt_tp: `['.user.yml', 'dependencies.yml', 'profiles.yml', 'snapshots', 'package-lock.yml', 'Dockerfile', 'tests', 'models', 'README.md', 'macros', '.dockerignore', '.gitignore', 'seeds', 'analyses', 'dbt_project.yml']`
[2024-06-25T16:49:39.915+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:39.915+0000] {graph.py:262} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/run_dbt__dbt_task_group/target/partial_parse.msgpack
[2024-06-25T16:49:39.922+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:39.921+0000] {base.py:222} INFO - Using mock values for profile dbt_tp
[2024-06-25T16:49:39.923+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:39.923+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=True at /tmp/tmp72mhi2la/profiles.yml with the following contents:
dbt_tp:
    outputs:
        dev:
            dbname: postgres
            host: mock_value
            password: mock_value
            port: 5432
            schema: public
            type: postgres
            user: mock_value
    target: dev
[2024-06-25T16:49:39.923+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:39.923+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt deps --project-dir /tmp/tmpeypvhca7 --profiles-dir /tmp/tmp72mhi2la --profile dbt_tp --target dev`
[2024-06-25T16:49:44.221+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:44.220+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt ls --output json --project-dir /tmp/tmpeypvhca7 --profiles-dir /tmp/tmp72mhi2la --profile dbt_tp --target dev`
[2024-06-25T16:49:45.660+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:45.660+0000] {graph.py:190} INFO - Total nodes: 6
[2024-06-25T16:49:45.661+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:45.660+0000] {graph.py:191} INFO - Total filtered nodes: 6
[2024-06-25T16:49:45.662+0000] {processor.py:840} INFO - DAG(s) 'run_dbt' retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:49:45.672+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:45.672+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-25T16:49:45.676+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:49:45.676+0000] {dag.py:3954} INFO - Setting next_dagrun for run_dbt to None, run_after=None
[2024-06-25T16:49:45.684+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 5.794 seconds
[2024-06-25T16:50:15.893+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/run_dbt.py
[2024-06-25T16:50:15.894+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/run_dbt.py for tasks to queue
[2024-06-25T16:50:15.897+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:50:15.896+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:50:15.906+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:50:15.906+0000] {graph.py:242} INFO - Trying to parse the dbt project in `/opt/airflow/dbt_tp` using dbt ls...
[2024-06-25T16:50:15.908+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:50:15.908+0000] {graph.py:252} INFO - Content of the dbt project dir /opt/airflow/dbt_tp: `['.user.yml', 'dependencies.yml', 'profiles.yml', 'snapshots', 'package-lock.yml', 'Dockerfile', 'tests', 'models', 'README.md', 'macros', '.dockerignore', '.gitignore', 'seeds', 'analyses', 'dbt_project.yml']`
[2024-06-25T16:50:15.910+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:50:15.910+0000] {graph.py:262} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/run_dbt__dbt_task_group/target/partial_parse.msgpack
[2024-06-25T16:50:15.919+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:50:15.919+0000] {base.py:222} INFO - Using mock values for profile dbt_tp
[2024-06-25T16:50:15.920+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:50:15.920+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=True at /tmp/tmprxeo1pal/profiles.yml with the following contents:
dbt_tp:
    outputs:
        dev:
            dbname: postgres
            host: mock_value
            password: mock_value
            port: 5432
            schema: public
            type: postgres
            user: mock_value
    target: dev
[2024-06-25T16:50:15.921+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:50:15.921+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt deps --project-dir /tmp/tmpgncrk73d --profiles-dir /tmp/tmprxeo1pal --profile dbt_tp --target dev`
[2024-06-25T16:50:18.723+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:50:18.722+0000] {graph.py:76} INFO - Running command: `/usr/local/bin/dbt ls --output json --project-dir /tmp/tmpgncrk73d --profiles-dir /tmp/tmprxeo1pal --profile dbt_tp --target dev`
[2024-06-25T16:50:20.324+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:50:20.324+0000] {graph.py:190} INFO - Total nodes: 6
[2024-06-25T16:50:20.325+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:50:20.325+0000] {graph.py:191} INFO - Total filtered nodes: 6
[2024-06-25T16:50:20.327+0000] {processor.py:840} INFO - DAG(s) 'run_dbt' retrieved from /opt/airflow/dags/run_dbt.py
[2024-06-25T16:50:20.339+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:50:20.339+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-25T16:50:20.343+0000] {logging_mixin.py:188} INFO - [2024-06-25T16:50:20.343+0000] {dag.py:3954} INFO - Setting next_dagrun for run_dbt to None, run_after=None
[2024-06-25T16:50:20.354+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/run_dbt.py took 4.469 seconds
